spring:    
    application:        
        name:  SpringBootRest
    datasource:        
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 1234 
        url: jdbc:mysql://localhost:8080/rest_api_db    
    jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.MySQLDialect
      defer-datasource-initialization: true
      properties:
            hibernate:
              format_sql: true
      hibernate:
          ddl-auto: create-drop          
    springfox:
      documentation:
        swagger-ui:
          base-url: SpringBootRest